<!DOCTYPE html>
<html lang="en">

   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Sales</title>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap" rel="stylesheet">
      <link href="http://fonts.cdnfonts.com/css/helvetica-neue-9" rel="stylesheet">
      <link href="<?php echo get_template_directory_uri(); ?>/fonts/texgyretermes-bold.otf" rel="stylesheet">
      <link href="<?php echo get_template_directory_uri(); ?>/fonts/texgyretermes-bolditalic.otf" rel="stylesheet">
      <!-- CSS only -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
         integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <style>
         /* brand-color: #efc3b8 */
         @font-face {
            font-family: texgyretermes-bold;
            src: url('<?php echo get_template_directory_uri(); ?>/fonts/texgyretermes-bold.otf');
         }

         body {
            font-family: 'Quicksand', sans-serif;
         }
      </style>
   </head>

   <body>
   <section id="explain13milli-seconds">
         <div class="container">
         <div class="texgyretermesBold text-1 mb-2" style="font-size: 18px;">
         EARNINGS DISCAlMER
  
        </div> 
            <div class="taxt-1 text-left mb-2">
               <div class="mb-1">
           
<p>NO EARNINGS PROJECTIONS, PROMISES, OR REPRESENTATIONS</p>
<p>YOU RECOGNIZE AND AGREE THAT WE HAVE MADE NO IMPLICATIONS, WARRANTIES, PROMISES, SUGGESTIONS, PROJECTIONS, REPRESENTATIONS, OR GUARANTEES WHATSOEVER TO YOU ABOUT FUTURE PROSPECTS OR EARNINGS, OR THAT YOU WILL EARN ANY MONEY, CONCERNING YOUR PURCHASE OF SONITHA MANDAVA&rsquo;S PRODUCTS, AND THAT WE HAVE NOT AUTHORIZED ANY SUCH PROJECTION, PROMISE, OR REPRESENTATION BY OTHERS.</p>

<p>ANY EARNINGS OR INCOME STATEMENTS, OR ANY EARNINGS OR INCOME EXAMPLES, ARE ONLY ESTIMATES OF WHAT WE THINK YOU COULD EARN. THERE IS NO ASSURANCE YOU WILL DO AS WELL AS STATED IN ANY EXAMPLES. IF YOU RELY UPON ANY FIGURES PROVIDED, YOU MUST ACCEPT THE ENTIRE RISK OF NOT DOING AS WELL AS THE INFORMATION PROVIDED. THIS APPLIES WHETHER THE EARNINGS OR INCOME EXAMPLES ARE MONETARY IN NATURE OR PERTAIN TO ADVERTISING CREDITS THAT MAY BE EARNED (WHETHER SUCH CREDITS ARE CONVERTIBLE TO CASH OR NOT).</p>

<p>THERE IS NO ASSURANCE THAT ANY PRIOR SUCCESSES OR PAST RESULTS AS TO EARNINGS OR INCOME (WHETHER MONETARY OR ADVERTISING CREDITS, WHETHER CONVERTIBLE TO CASH OR NOT) WILL APPLY, NOR CAN ANY PRIOR SUCCESSES BE USED, AS AN INDICATION OF YOUR FUTURE SUCCESS OR RESULTS FROM ANY OF THE INFORMATION, CONTENT, OR STRATEGIES. ANY AND ALL CLAIMS OR REPRESENTATIONS AS TO INCOME OR EARNINGS (WHETHER MONETARY OR ADVERTISING CREDITS, WHETHER CONVERTIBLE TO CASH OR NOT) ARE NOT TO BE CONSIDERED AS &ldquo;AVERAGE EARNINGS&rdquo;.</p>

<p>THE ECONOMY, BOTH WHERE YOU DO BUSINESS, AND ON A NATIONAL AND EVEN WORLDWIDE SCALE, CREATES ADDITIONAL UNCERTAINTY AND ECONOMIC RISK. AN ECONOMIC RECESSION OR DEPRESSION MIGHT NEGATIVELY AFFECT YOUR RESULTS.</p>

<p>YOUR SUCCESS IN USING THE INFORMATION OR STRATEGIES PROVIDED BY KRITI NAYAR&apos;s COURSES DEPENDS ON A VARIETY OF FACTORS. WE HAVE NO WAY OF KNOWING HOW WELL YOU WILL DO, AS WE DO NOT KNOW YOU, YOUR BACKGROUND, YOUR WORK ETHIC, YOUR DEDICATION, YOUR MOTIVATION, YOUR DESIRE, OR YOUR BUSINESS SKILLS OR PRACTICES. THEREFORE, WE DO NOT GUARANTEE OR IMPLY THAT YOU WILL GET RICH, THAT YOU WILL DO AS WELL, OR THAT YOU WILL HAVE ANY EARNINGS (WHETHER MONETARY OR ADVERTISING CREDITS, WHETHER CONVERTIBLE TO CASH OR NOT), AT ALL.</p>

<p>INTERNET BUSINESS AND EARNINGS DERIVED THEREFROM, INVOLVE UNKNOWN RISKS AND ARE NOT SUITABLE FOR EVERYONE. YOU MAY NOT RELY ON ANY INFORMATION PRESENTED ON THE WEBSITE OR OTHERWISE PROVIDED BY US UNLESS YOU DO SO WITH THE KNOWLEDGE AND UNDERSTANDING THAT YOU CAN EXPERIENCE SIGNIFICANT LOSSES INCLUDING, BUT NOT LIMITED TO, THE LOSS OF ANY MONIES PAID TO PURCHASE KRITI NAYAR&rsquo;s COURSES &amp; PRODUCTS, AND/OR ANY MONIES SPENT SETTING UP, OPERATING, AND/OR MARKETING YOUR OWN PRODUCTS, AND FURTHER, THAT YOU MAY HAVE NO EARNINGS AT ALL (WHETHER MONETARY OR ADVERTISING CREDITS, WHETHER CONVERTIBLE TO CASH OR NOT).</p>

<p>MATERIALS CONTAINED ON THE WEBSITE OR IN MATERIALS PURCHASED AND/OR DOWNLOADED TO THE WEBSITE MAY CONTAIN INFORMATION THAT INCLUDES OR IS BASED UPON FORWARD-LOOKING STATEMENTS WITHIN THE MEANING OF THE SECURITIES LITIGATION REFORM ACT OF 1995. FORWARD-LOOKING STATEMENTS GIVE OUR EXPECTATIONS OR FORECASTS OF FUTURE EVENTS. YOU CAN IDENTIFY THESE STATEMENTS BY THE FACT THAT THEY DO NOT RELATE STRICTLY TO HISTORICAL OR CURRENT FACTS. THEY USE WORDS SUCH AS &ldquo;ANTICIPATE,&rdquo; &ldquo;ESTIMATE,&rdquo; &ldquo;EXPECT,&rdquo; &ldquo;PROJECT,&rdquo; &ldquo;INTEND,&rdquo; &ldquo;PLAN,&rdquo; &ldquo;BELIEVE,&rdquo; AND OTHER WORDS AND TERMS OF SIMILAR MEANING IN CONNECTION WITH A DESCRIPTION OF POTENTIAL EARNINGS OR FINANCIAL PERFORMANCE.</p>

<p>ANY AND ALL FORWARD-LOOKING STATEMENTS HERE, IN OTHER MATERIALS CONTAINED ON THIS WEBSITE, OR IN MATERIALS PURCHASED AND/OR DOWNLOADED FROM THIS WEBSITE ARE INTENDED TO EXPRESS OUR OPINION OF EARNINGS POTENTIAL. MANY FACTORS WILL BE IMPORTANT TO DETERMINE YOUR ACTUAL RESULTS AND NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE RESULTS SIMILAR TO OURS OR ANYBODY ELSE, IN FACT, NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE ANY RESULTS FROM OUR IDEAS AND TECHNIQUES IN OUR MATERIAL.</p>

<p>YOU ARE ADVISED TO DO YOUR OWN DUE DILIGENCE WHEN IT COMES TO MAKING BUSINESS DECISIONS AND SHOULD USE CAUTION AND SEEK THE ADVICE OF QUALIFIED PROFESSIONALS. YOU SHOULD CHECK WITH YOUR ACCOUNTANT, LAWYER, OR PROFESSIONAL ADVISOR, BEFORE ACTING ON THIS OR ANY INFORMATION. YOU MAY NOT CONSIDER ANY EXAMPLES, DOCUMENTS, OR OTHER CONTENT ON THE WEBSITE OR OTHERWISE PROVIDED BY US TO BE THE EQUIVALENT OF PROFESSIONAL ADVICE. NOTHING CONTAINED ON THE WEBSITE OR IN MATERIALS AVAILABLE FOR SALE OR DOWNLOAD ON THE WEBSITE PROVIDES PROFESSIONAL ADVICE IN ANY WAY. YOU SHOULD CONSULT WITH YOUR OWN ACCOUNTANT, LAWYER, OR PROFESSIONAL ADVISOR FOR ANY QUESTIONS YOU MAY HAVE.</p>

<p>WE ASSUME NO RESPONSIBILITY FOR ANY LOSSES OR DAMAGES RESULTING FROM YOUR USE OF ANY LINK, INFORMATION, OR OPPORTUNITY CONTAINED WITHIN THE WEBSITE OR WITHIN ANY INFORMATION DISCLOSED BY THE OWNER OF THIS SITE IN ANY FORM WHATSOEVER.</p>

<p>ALTHOUGH WE BELIEVE THE PRICE IS FAIR FOR THE VALUE THAT YOU RECEIVE, YOU UNDERSTAND AND AGREE THAT THE PURCHASE PRICE FOR KRITI NAYAR&rsquo;S COURSES AND PRODUCTS HAS BEEN ARBITRARILY SET BY US. THIS PRICE BEARS NO RELATIONSHIP TO OBJECTIVE STANDARDS.</p>
<p><br></p>
              
            </div>
      
         </div>
      </section>
 

     